---
name: pre-release
on:
  push:
    tags:
      - v*-rc*

jobs:
  prerelease:
    name: pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: import GPG signing key
        run: |
          gpg-agent --daemon
          echo '${{ secrets.GPG_PRIVATE_KEY }}' | gpg --import
      - run: make debug sign
      - name: pre-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
